### ISSUE TITLE
Error running render-example.sh example script

### ISSUE THREAD

**Issue by umerebryx** [awentzonline/image-analogies#29]
While running one of the example scripts I am running into following issue:

./render-example.sh arch ../vgg16_weights.h5 
Only using analogy loss
Using Theano backend.
Using gpu device 0: Tesla K80 (CNMeM is enabled with initial size: 90.0% of memory, CuDNN 3007)
Using brute-force model
Scale factor 0.25 "A" shape (1, 3, 116, 80) "B" shape (1, 3, 128, 89)
Building loss...
Precomputing static features...
Traceback (most recent call last):
  File "/usr/local/bin/make_image_analogy.py", line 5, in <module>
    pkg_resources.run_script('neural-image-analogies==0.0.11', 'make_image_analogy.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/neural_image_analogies-0.0.11-py2.7.egg/EGG-INFO/scripts/make_image_analogy.py", line 27, in <module>
    
  File "build/bdist.linux-x86_64/egg/image_analogy/main.py", line 69, in main
  File "build/bdist.linux-x86_64/egg/image_analogy/models/base.py", line 23, in build
  File "build/bdist.linux-x86_64/egg/image_analogy/models/analogy.py", line 23, in build_loss
  File "build/bdist.linux-x86_64/egg/image_analogy/models/base.py", line 53, in precompute_static_features
  File "build/bdist.linux-x86_64/egg/image_analogy/models/base.py", line 61, in get_features
  File "build/bdist.linux-x86_64/egg/image_analogy/models/base.py", line 72, in get_layer_output
AttributeError: 'Convolution2D' object has no attribute 'get_output'

Any idea what is wrong here. Any help would be really appreciated. Thanks

**Comment by umerebryx** [comment]
I solved this, apparently in Keras 1.0.2 get_output() is deprecated. Change the following code in model.base.py:
self._f_layer_outputs[name] = layer.get_output()
to
self._f_layer_outputs[name] = layer.output

worked for me.
