### ISSUE TITLE
module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

### ISSUE THREAD

**Issue by taktikal17** [awentzonline/image-analogies#42]
Hi, 

I was trying to run:
`make_image_analogy.py images/arch-mask.jpg images/arch.jpg images/arch-newmask.jpg out/arch`

When I got this:

`AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'`

Any idea how to fix that?

Thank you!

**Comment by RSudarsanan** [comment]
Hi,
I had this same error when I was trying to import keras which uses tensorflow in the backend.
Then I re-installed tensorflow with virtual environment. Now the error has gone. I am not sure if this may help. I followed the "Installing with Virtualenv" section in this site : https://www.tensorflow.org/install/install_linux
And then maybe you can run the program in the virtual environment

**Comment by husnejahan** [comment]
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

Same error when using keras where tensorflow as backend

**Comment by ghost** [comment]
Hi,
I have tried by installing the tensorflow with virtualenv but the erroe was same. 
Any idea how to fix that?

(venv) pi@raspberrypi:~ $ python3 /home/pi/Desktop/final\ face/facenet\ face\ recognition/facenet.py 
Using TensorFlow backend.

** (facenet.py:27420): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "/home/pi/Desktop/final face/facenet face recognition/facenet.py", line 19, in <module>
    FRmodel = faceRecoModel(input_shape=(3, 96, 96))
  File "/home/pi/Desktop/final face/facenet face recognition/inception_blocks_v2.py", line 229, in faceRecoModel
    X = ZeroPadding2D((3, 3))(X_input)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 279, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "/home/pi/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 470, in is_keras_tensor
    if not is_tensor(x):
  File "/home/pi/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 478, in is_tensor
    return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

**Comment by th4t-gi** [comment]
I got the exact same error as @taktikal17 but with a `keras.layers.LSTM` instance. I am running this on OSX 10.11 so I had to install tensorflow/keras with virtualenv. Pretty sure my OS is my problem but it might not...

**Comment by wanlitengfei** [comment]
i use version tensorflow==1.10.0 with no problem

**Comment by Jay2109** [comment]
I am getting same error while using ImageAI

**Comment by Rahul2991** [comment]
Just fix the imports like
from keras import import Sequential

to this:
tensorflow.keras import Sequential

Similarly for other imports starting with 'from keras'

**Comment by mansi-aggarwal-2504** [comment]
> I am getting same error while using ImageAI

I am also getting this error while using ImageAI. Referring to [this](https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff).

**Comment by Aryan2472** [comment]
good
