### ISSUE TITLE
ValueError: Function has keyword-only arguments or annotations,

### ISSUE THREAD

**Issue by PaulLantos** [awentzonline/image-analogies#47]
Hi,
 I'm getting the following error and not sure how to fix it. Thanks for any help.
Paul

 make_image_analogy.py input/img1b.jpg input/img1a.jpg input/IMG_0006_12.jpg output/img2.jpg --vgg-weights=vgg16_weights.h5 --height=500 --a-scale-mode=match --patch-size=5 --scales=5 --mrf-w=0.2

Using TensorFlow backend.
Traceback (most recent call last):
  File "/dscrhome/pl39/anaconda3/bin/make_image_analogy.py", line 12, in <module>
    import image_analogy.argparser
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/image_analogy/argparser.py", line 4, in <module>
    from keras import backend as K
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/keras/backend/__init__.py", line 69, in <module>
    from .tensorflow_backend import *
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 65, in <module>
    import tensorflow.contrib as contrib
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 30, in <module>
    from tensorflow.contrib import learn
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 72, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.autoencoder import TensorFlowDNNAutoencoder
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/autoencoder.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.base import TensorFlowBaseTransformer
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 34, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 39, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/dask/dataframe/__init__.py", line 1, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py", line 23, in <module>
    from .. import array as da
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/dask/array/__init__.py", line 4, in <module>
    from .core import (Array, stack, concatenate, take, tensordot, transpose,
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/dask/array/core.py", line 13, in <module>
    from toolz.curried import (pipe, partition, concat, unique, pluck, join, first,
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 53, in <module>
    _curry_namespace(vars(toolz)),
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 48, in _curry_namespace
    for name, f in ns.items() if '__' not in name
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 48, in <genexpr>
    for name, f in ns.items() if '__' not in name
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 42, in _should_curry
    return (callable(f) and _nargs(f) > 1 or f in do_curry)
  File "/dscrhome/pl39/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 35, in _nargs
    return len(inspect.getargspec(f).args)
  File "/dscrhome/pl39/anaconda3/lib/python3.5/inspect.py", line 1050, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them

**Comment by vidyasagarr7** [comment]
I get the same error when importing keras. Any ideas ?
