### ISSUE TITLE
a-scale parameter doesn't work with Theano

### ISSUE THREAD

**Issue by NotRobert** [awentzonline/image-analogies#54]
The parameter --a_scale work well with tensorflow.
But with theano, I get the following error (example with "--a-scale=1.2") :

_Scale factor 0.25 "A" shape (1, 3, 540, 720) "B" shape (1, 3, 450, 600)
Building loss...
Precomputing static features...
Traceback (most recent call last):
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Shape error. v->dimensions[2] = 540, a->dimesions[2 + 0] = 450_

And more detail :

_During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts/make_image_analogy.py", line 27, in <module>
    image_analogy.main.main(args, model_class)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/main.py", line 167, in main
    model.build(a_image, ap_image, b_image, (1, img_num_channels, img_height, img_width))
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/models/nnf.py", line 17, in build
    loss = self.build_loss(a_image, ap_image, b_image)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/models/nnf.py", line 55, in build_loss
    all_a_features, all_ap_image_features, all_b_features = self.precompute_static_features(a_image, ap_image, b_image)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/models/base.py", line 53, in precompute_static_features
    all_a_features = self.get_features(a_image, a_layers)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/models/base.py", line 62, in get_features
    feature_outputs = f([x])
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 1388, in __call__
    return self.function(*inputs)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Shape error. v->dimensions[2] = 540, a->dimesions[2 + 0] = 450
Apply node that caused the error: GpuIncSubtensor{InplaceSet;::, ::, int64:int64:, int64:int64:}(GpuAlloc<None>{memset_0=True}.0, GpuElemwise{Add}[(0, 0)]<gpuarray>.0, Constant{1}, Constant{451}, Constant{1}, Constant{601})
Toposort index: 82
Inputs types: [GpuArrayType<None>(float32, 4D), GpuArrayType<None>(float32, 4D), Scalar(int64), Scalar(int64), Scalar(int64), Scalar(int64)]
Inputs shapes: [(1, 64, 452, 602), (1, 64, 540, 720), (), (), (), ()]
Inputs strides: [(69658624, 1088416, 2408, 4), (99532800, 1555200, 2880, 4), (), (), (), ()]
Inputs values: ['not shown', 'not shown', 1, 451, 1, 601]
Outputs clients: [[GpuContiguous(GpuIncSubtensor{InplaceSet;::, ::, int64:int64:, int64:int64:}.0)]]
Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "scripts/make_image_analogy.py", line 27, in <module>
    image_analogy.main.main(args, model_class)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/main.py", line 115, in main
    net = vgg16.get_model(img_width, img_height, weights_path=args.vgg_weights, pool_mode="avg")
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/image_analogy/vgg16.py", line 42, in get_model
    model.add(ZeroPadding2D((1, 1)))
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/keras/engine/sequential.py", line 181, in add
    output_tensor = layer(self.outputs[0])
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/keras/layers/convolutional.py", line 2231, in call
    data_format=self.data_format)
  File "/home/kassius/anaconda3/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 1193, in spatial_2d_padding
    y = T.set_subtensor(output[indices], x)_

Running without "--a-scale" parameter work like a charm.
Changing "--a-scale-mode" doesn't help.
Any idea?

**Comment by NotRobert** [comment]
Keras version was 2.x
Downgrading to Keras 1.x has solved the issue.
